apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-11-11T13:21:19Z"
  generation: 1
  labels:
    app: nginx-demo
  name: nginx-demo
  namespace: demo
  resourceVersion: "40448"
  uid: b355bece-4cb5-4efb-a3f6-c931a8805828
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-demo
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
