apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-redis
  name: new-redis
spec:
  containers:
  - image: redis
    name: new-redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
status: {}
