apiVersion:  v1
kind:  Service
metadata: 
  name:  clusterip-svc
  labels:
    env: demo
spec:
  ports:
  - port:  8080
    targetPort:  80
  selector:
    env:  demo 
    pod-template-hash:  84bdb68cd5
