apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    env: demo
  name: lb1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    env: demo
  type: LoadBalancer
status:
  loadBalancer: {}
