apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: demo
  name: nginx-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      env: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        env: demo
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
