apiVersion:  v1
kind:  Service
metadata: 
  name:  nodeport-svc
  labels:
    env: demo
spec:
  type:  NodePort
  ports:
  - nodePort: 30001
    port:  8080
    targetPort:  80
  selector:
    env:  demo 
    pod-template-hash:  84bdb68cd5
