apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy/new-deploy
  name: deploy/new-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy/new-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy/new-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
