apiVersion:  apps/v1
kind:  Deployment
metadata:  
  name: nginx-deploy
  labels:
    env: demo
spec:
  template:
    metadata:
      name: nginx-deploy
      labels:
        env:  demo
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas:  2
  selector:
    matchLabels:
      env: demo
        